### PR TITLE
Move code generation into an integration test

### PR DESCRIPTION
**Pull request by djc**
Instead of using a build script, use an integration test to generate code from the input files. This makes it so that downstream users don't have to compile and run the build script, and allows the crate to work more easily with non-Cargo build systems (like Buck2) that require deterministic input. The integration test will fail CI if the generated code falls out of sync with the input.

### CODE REVIEW

**Comment by picoHz** [comment]
I don't think generating code in the integration test is a good idea.
Could you just add the code generator as a binary target?

**Comment by djc** [comment]
Why don't you think it is a good idea? Participants of the performance working group have repeatedly said that build scripts are problematic for performance since they introduce an extra step in the compilation pipeline. It's just a waste of time and resources to have all downstream consumers redo the work that you could be doing at development time.

Several other crates have adopted similar solutions:

* https://github.com/async-graphql/async-graphql/pull/901
* https://github.com/steveklabnik/semver-parser/pull/50
* https://github.com/mattsse/chromiumoxide/pull/80
* https://github.com/humenda/isolang-rs/pull/30

**Comment by picoHz** [comment]
I'm not against removing the build script, but I am skeptical about the use of the test script hack for code generation. However, it is also true that your solution does not seem to have obvious drawbacks.

**Comment by picoHz** [comment]
Because it's not what the test script is intended for. For instance, when another program depends on this repo as a path dependency, the code generation isn't triggered by updating names.txt, unlike when using build.rs. Although this might not be a major issue, it can still cause confusion.

**Comment by djc** [comment]
That's a fair point, thanks for explaining!

**Pull request merged**
